# Generated by Django 3.0.4 on 2020-03-20 17:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(max_length=25)),
                ('modelo', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Gasto',
            },
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('renta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.Carros')),
            ],
            options={
                'verbose_name_plural': 'Rentas',
            },
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Propietarios',
                'unique_together': {('nombres', 'apellidos')},
            },
        ),
        migrations.CreateModel(
            name='Polizas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('aseguradora', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio_poliza', models.DateField(blank=True, null=True)),
                ('fin_poliza', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='polizas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carros.Carros')),
            ],
            options={
                'verbose_name_plural': 'Polizas',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('semana', models.CharField(max_length=20)),
                ('startweek', models.DateField(blank=True, null=True)),
                ('endweek', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.Carros')),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carros.Renta')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Inactividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carros.Carros')),
            ],
            options={
                'verbose_name_plural': 'Razon de Inactividad',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('iva', models.BooleanField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('factura', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.Carros')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carros.TipoGasto')),
            ],
            options={
                'verbose_name_plural': 'Gastos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('ine', models.FileField(blank=True, null=True, upload_to='INE/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Conductores',
                'unique_together': {('nombres', 'apellidos')},
            },
        ),
        migrations.AddField(
            model_name='carros',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carros.Conductores'),
        ),
        migrations.AddField(
            model_name='carros',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.Propietarios'),
        ),
    ]
