# Generated by Django 3.0.4 on 2020-03-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'verbose_name_plural': 'Gastos'},
        ),
    ]
