# Generated by Django 3.0.4 on 2020-03-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_auto_20200324_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AddField(
            model_name='gasto',
            name='semana',
            field=models.CharField(default='2020-W12', max_length=20),
            preserve_default=False,
        ),
    ]
