# Generated by Django 3.0.4 on 2020-04-24 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_auto_20200325_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carros',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Vehículos'},
        ),
    ]
