# Generated by Django 3.0.4 on 2020-04-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_auto_20200424_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagos',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'Pagos'},
        ),
    ]
