# Generated by Django 3.0.4 on 2020-04-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_auto_20200424_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductores',
            options={'ordering': ['nombres'], 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterModelOptions(
            name='polizas',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Polizas'},
        ),
    ]
