# Generated by Django 3.0.5 on 2020-05-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_auto_20200424_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductores',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='compdom/'),
        ),
        migrations.AddField(
            model_name='conductores',
            name='licencia',
            field=models.FileField(blank=True, null=True, upload_to='licencia/'),
        ),
    ]
